before_script:
  - export ANDROID_HOME=/opt/android-sdk
  - export PATH=$PATH:/opt/android-sdk/tools
  - export PATH=$PATH:/opt/android-sdk/tools/bin
  - export PATH=$PATH:/opt/android-sdk/platform-tools
  - chmod +x gradlew
  - sdkmanager "platforms;android-26"
  - sdkmanager "build-tools"
  - sdkmanager "tools"
  - sdkmanager "platform-tools"
  - sdkmanager "extras;android;m2repository"
  - sdkmanager "extras;google;google_play_services"
  - sdkmanager "extras;google;m2repository"

stages:
  - build

debug:
  stage: build
  except:
    - release
  script:
    - ./gradlew assembleDebug

release:
  stage: build
  only:
    - release
  script:
    - ./gradlew assembleRelease