before_script:
  - export ANDROID_HOME=/opt/android-sdk
  - export ANDROID_HOME=/opt/android-sdk
  - export PATH=$PATH:/opt/android-sdk/tools
  - export PATH=$PATH:/opt/android-sdk/platform-tools
  - chmod +x gradlew

stages:
  - build
  - test
  - cleanup

AndroidBuild:
  stage: build
  script:
    - ./gradlew build
  tags:
    - android

AndroidTest:
  stage: test
  script:
    - emulator -avd android -no-audio -no-window
    - /opt/android-sdk/android-wait-for-emulator
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest
  tags:
     - android

AndroidCleanup:
  stage: cleanup
  when: always
  allow_failure: true
  script:
    - pgrep emulator | xargs kill -9
  tags:
    - android