before_script:
  - export ANDROID_HOME="/opt/android-sdk"
  - chmod +x gradlew
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | /opt/android-sdk/tools/android update sdk -u -a -t 1,3,29,140,147,148

build:
  script:
  - ./gradlew build
  tags:
    - android